### ISSUE TITLE
[wip] Proposal for a Data Model

### ISSUE THREAD

**Issue by grekko** [brettspielpony/TwilightImperiumGameTracker#4]
## Basis Data Structure

A Twilight Imperium game could be modeled with:
- `Game`: A single game session, tracking metadata about the game (who won, who took mecatol, …) and ties together all entities
- `Player`: Describing each Players basic Setting like their seating at the table, their Faction, Name
- `Round`: Tracking the most important changes thorugh each round, e.g. the opened Public Objectives, the picked Stragey Cards and scored Victory Points

### Games

| id | short_id | Title | created_at | custodion\_round | custodian\_faction |
| --- | --- | --- | --- | --- | --- |
| 1 | kcFx12 | Tondorf | 2020-02-22 09:12:12 | 2 | L1z1x |

### Player

| id | game_id | name | position | faction |
| --- | --- | --- | --- | --- |
| 1 | 1 | Greg | 1 | L1z1x |
| 2 | 1 | Dirk | 2 | Barony |
| 3 | 1 | Essy | 3 | Hacan |
| 4 | 1 | Basti | 4 | Ghost of Creuss |
| 5 | 1 | Björn | 5 | Sol |
| 6 | 1 | Marc | 6 | Sardakk Norr |

**Comment by code-later** [comment]
@grekko I really like the approach you presented here. Only thing that comes to mind right now: How about to store the map string along the `Game` entity?
